### ISSUE TITLE
label: Person

### ISSUE THREAD

**Issue by devipramita** [incheon-kim/yolov4-deepsort-helmet-detection#1]
Hi, I've tried running your yolov4 models for inference without the deepsort, i want to know do you have any case that shows up the label "person"? As long as i run the models, it always give only 2 labels (helmet & head). Thanks!

**Comment by incheon-kim** [comment]
The label "person" is just dummy label. So it won't appear in any cases .Originally I planned to have three labels and determine it is valid if bbox of heltmet and person is overlapped. As you can see I didn't and I forgot to delete that even during training :)

Hope it was helpful.

**Comment by devipramita** [comment]
ah i see, alright thanks a lot Kim
