### ISSUE TITLE
AttributeError: I can't find where is "copy_image_from_bytes"

### ISSUE THREAD

**Issue by yagippi27** [incheon-kim/yolov4-deepsort-helmet-detection#2]
When I do "python detect_image.py" or "python detectandtrack.py",

> Traceback (most recent call last):
>   File "detect_image.py", line 8, in <module>
>     import darknet
>   File "/home/hyun/yolov4-deepsort-helmet-detection/darknet.py", line 137, in <module>
>     copy_image_from_bytes = lib.copy_image_from_bytes
>   File "/home/hyun/miniconda3/envs/test/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
>     func = self.__getitem__(name)
>   File "/home/hyun/miniconda3/envs/test/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
>     func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: ./libdarknet.so: undefined symbol: copy_image_from_bytes

Above things showed up.
How can I fix it?
Even I coudn't find where copy_image_from_bytes define.

And Can I make libdarknet.so using pjreddie/darknet?

**Comment by incheon-kim** [comment]
You can build yourself from https://github.com/AlexeyAB/darknet . And I built myself with code from there.

**Comment by yagippi27** [comment]
> You can build yourself from https://github.com/AlexeyAB/darknet . And I built myself with code from there.

Thank you for answering!
